# Generated by Django 5.1.1 on 2024-09-28 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinataKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='returned_image',
            field=models.ManyToManyField(null=True, related_name='processed_pinata_key', to='imageApi.pinatakey'),
        ),
        migrations.AddField(
            model_name='image',
            name='uploaded_image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_pinata_key', to='imageApi.pinatakey'),
        ),
    ]
