# Generated by Django 5.1.1 on 2024-09-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageApi', '0002_pinatakey_remove_image_image_image_returned_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='returned_image',
            field=models.ManyToManyField(related_name='processed_pinata_key', to='imageApi.pinatakey'),
        ),
    ]
