# Generated by Django 5.1.1 on 2024-09-29 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageApi', '0004_alter_image_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='returned_image',
        ),
        migrations.AddField(
            model_name='image',
            name='returned_1',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returned_key_1', to='imageApi.pinatakey'),
        ),
        migrations.AddField(
            model_name='image',
            name='returned_2',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returned_key_2', to='imageApi.pinatakey'),
        ),
        migrations.AddField(
            model_name='image',
            name='returned_3',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returned_key_3', to='imageApi.pinatakey'),
        ),
    ]
